---

- name: Key of repo add
  apt_key:
    id: D68FA50FEA312927
    keyserver: keyserver.ubuntu.com
    state: present
  tags: install

- name: Repo add
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    filename: mongodb-org-3.2
  tags: install

- name: Install mongodb-org
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  tags: install

- name: Enable mongod
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
